In [1]:
import numpy as np
import pandas as pd
import random
from sklearn.ensemble import RandomForestRegressor
from timeit import default_timer as timer
import time
import sys, getopt
import math
from sklearn.model_selection import GridSearchCV

In [2]:
import os

os.chdir('/lustre/project/Stat/s1155168529/programs/DDML/code/real_data')
os.getcwd()

'/lustre/project/Stat/s1155168529/programs/DDML/code/real_data'

In [3]:
n_iter = 1
K = 3  #number of sites 
K_fold = 3
n_rft = 50

In [4]:
vec_beta_est_iter = np.zeros(n_iter)
adni1_pd = pd.read_csv('adni1.csv')
adni2_pd = pd.read_csv('adni2.csv')
adnigo_pd = pd.read_csv('adnigo.csv')
adni1= adni1_pd.values
adni2= adni2_pd.values
adnigo= adnigo_pd.values

In [6]:
df = [adni1, adni2, adnigo]

In [8]:
model = RandomForestRegressor()

param_grid = {
    'n_estimators': [20, 50, 100, 200],
    'max_depth': [None, 5, 10, 20, 30],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 5, 10]
}

# Setup the grid search
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='neg_mean_squared_error', verbose=1)

# Fit grid search
best_model1_d = grid_search.fit(df[0][:,6:20], df[0][:,22])

# Get the best parameters
print("Best parameters:", best_model1_d.best_params_)


Fitting 3 folds for each of 240 candidates, totalling 720 fits
Best parameters: {'max_depth': 5, 'min_samples_leaf': 10, 'min_samples_split': 10, 'n_estimators': 100}


In [9]:
param_grid = {
    'n_estimators': [20, 50, 100],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 5, 10]
}

# Setup the grid search
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='neg_mean_squared_error', verbose=1)

# Fit grid search
best_model1_y = grid_search.fit(df[0][:,6:20], df[0][:,21])

# Get the best parameters
print("Best parameters:", best_model1_y.best_params_)



Fitting 3 folds for each of 108 candidates, totalling 324 fits
Best parameters: {'max_depth': 5, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}


In [10]:
param_grid = {
    'n_estimators': [20, 50, 100],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 5, 10]
}

# Setup the grid search
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='neg_mean_squared_error', verbose=1)

# Fit grid search
best_model2_d = grid_search.fit(df[1][:,6:20], df[1][:,22])

# Get the best parameters
print("Best parameters:", best_model2_d.best_params_)

Fitting 3 folds for each of 108 candidates, totalling 324 fits
Best parameters: {'max_depth': 5, 'min_samples_leaf': 5, 'min_samples_split': 10, 'n_estimators': 50}


In [11]:
param_grid = {
    'n_estimators': [20, 50, 100],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 5, 10]
}

# Setup the grid search
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='neg_mean_squared_error', verbose=1)

# Fit grid search
best_model2_y = grid_search.fit(df[1][:,6:20], df[1][:,21])

# Get the best parameters
print("Best parameters:", best_model2_y.best_params_)

Fitting 3 folds for each of 108 candidates, totalling 324 fits
Best parameters: {'max_depth': 5, 'min_samples_leaf': 10, 'min_samples_split': 10, 'n_estimators': 20}


In [12]:
param_grid = {
    'n_estimators': [20, 50, 100],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 5, 10]
}

# Setup the grid search
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='neg_mean_squared_error', verbose=1)

# Fit grid search
best_model3_d = grid_search.fit(df[2][:,6:20], df[2][:,22])

# Get the best parameters
print("Best parameters:", best_model3_d.best_params_)

Fitting 3 folds for each of 108 candidates, totalling 324 fits
Best parameters: {'max_depth': 5, 'min_samples_leaf': 5, 'min_samples_split': 2, 'n_estimators': 20}


In [13]:
param_grid = {
    'n_estimators': [20, 50, 100],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 5, 10]
}

# Setup the grid search
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='neg_mean_squared_error', verbose=1)

# Fit grid search
best_model3_y = grid_search.fit(df[2][:,6:20], df[2][:,21])

# Get the best parameters
print("Best parameters:", best_model3_y.best_params_)

Fitting 3 folds for each of 108 candidates, totalling 324 fits
Best parameters: {'max_depth': 10, 'min_samples_leaf': 5, 'min_samples_split': 10, 'n_estimators': 20}


In [14]:
param_d = [best_model1_d.best_params_,best_model2_d.best_params_,best_model3_d.best_params_]
param_y = [best_model1_y.best_params_,best_model2_y.best_params_,best_model3_y.best_params_]

In [15]:
n1 = len(adni1)
n2 = len(adni2)
n3 = len(adnigo)

In [16]:
vec_weight = [n1, n2, n3]
vec_weight = vec_weight / np.sum(vec_weight)
vec_weight

array([0.45392491, 0.46211604, 0.08395904])

In [17]:
# Creating empty arrays with 0 rows but defined number of columns
array1 = [0]*n1
array2 = [0]*n2
array3 = [0]*n3

# Creating a list to contain these arrays
idx_K_fold = [array1, array2, array3]
idx_K_fold[0][0]

0

In [18]:
np.random.seed(1)
idx_K_fold[0] = np.random.choice(range(K_fold), n1, replace=True)

np.random.seed(1)
idx_K_fold[1] = np.random.choice(range(K_fold), n2, replace=True)

np.random.seed(1)
idx_K_fold[2] = np.random.choice(range(K_fold), n3, replace=True)

i_iter = 0
list_gamma_est = list()
list_mu_est = list()
mat_beta_est_local = np.zeros((K, K_fold))

## DDML initialization

In [19]:
for j in range(K):
    for splt in range(K_fold):
        idx_est = np.where(idx_K_fold[j] == splt)[0]
        idx_nui = np.where(idx_K_fold[j] != splt)[0]
        n_est = idx_est.shape[0]
        ## training ML model
        mat_X_nui = df[j][idx_nui, 6:20]
        vec_D_nui = df[j][idx_nui, 22]
        vec_Y_nui = df[j][idx_nui, 21]
                        
        ## estimating
        mat_X_est = df[j][idx_est, 6:20]
        vec_D_est = df[j][idx_est, 22]
        vec_Y_est = df[j][idx_est, 21]
        
        # model_mu = RandomForestRegressor(n_estimators=n_rft)
        model_mu = RandomForestRegressor(**param_d[j])
        model_mu.fit(mat_X_nui, vec_D_nui)
                        
        ## estimation of beta based on partialling out score function
        # model_xi = RandomForestRegressor(n_estimators=n_rft)
        model_xi = RandomForestRegressor(**param_y[j])
        model_xi.fit(mat_X_nui, vec_Y_nui)
                        
        vec_D_diff = vec_D_est - model_mu.predict(mat_X_est)
        vec_Y_diff = vec_Y_est - model_xi.predict(mat_X_est)
                        
        beta_est_local = np.mean(vec_Y_diff * vec_D_diff) / np.mean(vec_D_diff * vec_D_diff)

        model_gamma = RandomForestRegressor(n_estimators=50)
        model_gamma.fit(mat_X_nui, vec_Y_nui - vec_D_nui * beta_est_local)

        list_mu_est.append(model_mu)
        list_gamma_est.append(model_gamma)

        mat_beta_est_local[j, splt] = beta_est_local


In [20]:
mat_beta_est_local

array([[0.48587718, 0.5147843 , 0.39165601],
       [0.39363604, 0.45078038, 0.35658493],
       [0.17056276, 0.07644894, 0.16161799]])

In [21]:
print("mat_beta_est_local: ", mat_beta_est_local.mean(1))
print("beta_est_int (weighted): ", np.sum(mat_beta_est_local.mean(1) * vec_weight))
print("beta_est_ini (unweighted): ", mat_beta_est_local.mean())

mat_beta_est_local:  [0.46410583 0.40033378 0.1362099 ]
beta_est_int (weighted):  0.40710591409122115
beta_est_ini (unweighted):  0.333549836484168


## (Weighted) DDML

In [24]:
#DDML
beta_est_ini = np.sum(mat_beta_est_local.mean(1) * vec_weight)

vec_beta_est_cen = np.zeros(K)
vec_S_split = np.zeros(K_fold)
mat_U_slope_cen_split = np.zeros((K, K_fold))

for splt in range(K_fold): 
    for j in range(K):
        idx_est = np.where(idx_K_fold[j] == splt)[0]

        n_est = idx_est.shape[0]

        ## statistics from other sites
        vec_s = np.zeros(n_est)
        vec_S_est = np.zeros(K)
        idx_ls = j + splt * K

        ## estimating
        mat_X_est = df[j][idx_est, 6:20]
        vec_D_est = df[j][idx_est, 22]
        vec_Y_est = df[j][idx_est, 21]

        vec_D_diff = vec_D_est - list_mu_est[idx_ls].predict(mat_X_est)
        vec_Y_diff = vec_Y_est - list_gamma_est[idx_ls].predict(mat_X_est)
                        
        vec_s = (vec_Y_diff - vec_D_est * beta_est_ini) * vec_D_diff
                        
        vec_S_est[j] = np.mean(vec_s)
    
    # S = np.mean(vec_S_est) ## naive average
    S = np.sum(vec_S_est * vec_weight) ## weighted average
    vec_S_split[splt] = S
    
    for j_cen in range(K):
        idx_est = np.where(idx_K_fold[j] == splt)[0]

        n_est = idx_est.shape[0]
        
        idx_ls_cen = j_cen + splt * K

        vec_Y_cen = df[j_cen][idx_est, 21]
        vec_D_cen = df[j_cen][idx_est, 22]
        mat_X_cen = df[j_cen][idx_est,6:20]

        mat_U_slope = np.zeros((n_est, K))

        # single-equation density estimation
        vec_Y_cen_diff = vec_Y_cen - list_gamma_est[idx_ls_cen].predict(mat_X_cen)

        vec_U_cen_est = vec_Y_cen_diff - vec_D_cen * beta_est_ini
        for j in range(K):
            idx_ls = j + splt * K

            vec_D_loc_diff = vec_D_cen - list_mu_est[idx_ls].predict(mat_X_cen)

            vec_Y_loc_diff = vec_Y_cen - list_gamma_est[idx_ls].predict(mat_X_cen)
                            
            vec_U_loc_est = vec_Y_loc_diff - vec_D_cen * beta_est_ini
                            
            ## density ratio
            varU_loc = np.mean(np.power(vec_U_loc_est, 2))
            varU_cen = np.mean(np.power(vec_U_cen_est, 2))
            mat_U_slope[:, j] = np.power(vec_U_loc_est, 2)/(2*varU_loc) - np.power(vec_U_cen_est, 2)/(2*varU_cen)
            mat_U_slope[:, j] = np.exp(-1* mat_U_slope[:, j])
            mat_U_slope[:, j] = mat_U_slope[:, j] * math.sqrt(varU_cen)/math.sqrt(varU_loc)
            mat_U_slope[:, j] = mat_U_slope[:, j] * vec_D_cen * vec_D_loc_diff
            mat_U_slope[:, j] = mat_U_slope[:, j] * vec_weight[j]
        U_slope = np.mean(mat_U_slope.sum(1))

        mat_U_slope_cen_split[j_cen, splt] = U_slope
        
        # beta_est_cen = beta_est_ini + S / U_slope
        # mat_beta_est_cen[j_cen, splt] = beta_est_cen

# np.mean(vec_S_split) / mat_U_slope.mean(1)

# ## final estimation
# beta_est = np.mean(vec_beta_est_cen)
    
# vec_beta_est_iter[i_iter] = beta_est
        

In [25]:
vec_S_split

array([-0.00038022, -0.01870855, -0.01074039])

In [26]:
mat_U_slope_cen_split

array([[2.04413099, 1.38148581, 1.18081598],
       [0.81039925, 0.60458043, 1.08615952],
       [1.09643075, 1.11389988, 0.9050927 ]])

In [30]:
vec_beta_est_cen = beta_est_ini + np.mean(vec_S_split) / mat_U_slope_cen_split.mean(1)

In [31]:
print("(Weighted) vec_beta_est_cen average over data splitting: ", vec_beta_est_cen)
print("(Weighted) DDML estimator: ", np.sum(vec_beta_est_cen * vec_weight))

(Weighted) vec_beta_est_cen average over data splitting:  [0.39801699 0.39256631 0.39491786]
(Weighted) DDML estimator:  0.3952379414406314


## (Unweighted) DDML

In [ ]:
#DDML
beta_est_ini = mat_beta_est_local.mean()

mat_beta_est_cen = np.zeros((K, K_fold))

for splt in range(K_fold): 
    for j in range(K):
        idx_est = np.where(idx_K_fold[j] == splt)[0]

        n_est = idx_est.shape[0]

        ## statistics from other sites
        vec_s = np.zeros(n_est)
        vec_S_est = np.zeros(K)
        idx_ls = j + splt * K

        ## estimating
        mat_X_est = df[j][idx_est, 6:20]
        vec_D_est = df[j][idx_est, 22]
        vec_Y_est = df[j][idx_est, 21]

        vec_D_diff = vec_D_est - list_mu_est[idx_ls].predict(mat_X_est)
        vec_Y_diff = vec_Y_est - list_gamma_est[idx_ls].predict(mat_X_est)
                        
        vec_s = (vec_Y_diff - vec_D_est * beta_est_ini) * vec_D_diff
                        
        vec_S_est[j] = np.mean(vec_s)
    
    # S = np.sum(vec_S_est * vec_weight)
    S = np.mean(vec_S_est)
    
    for j_cen in range(K):
        idx_est = np.where(idx_K_fold[j] == splt)[0]

        n_est = idx_est.shape[0]
        
        idx_ls_cen = j_cen + splt * K

        vec_Y_cen = df[j_cen][idx_est, 21]
        vec_D_cen = df[j_cen][idx_est, 22]
        mat_X_cen = df[j_cen][idx_est,6:20]

        mat_U_slope = np.zeros((n_est, K))

        # single-equation density estimation
        vec_Y_cen_diff = vec_Y_cen - list_gamma_est[idx_ls_cen].predict(mat_X_cen)

        vec_U_cen_est = vec_Y_cen_diff - vec_D_cen * beta_est_ini
        for j in range(K):
            idx_ls = j + splt * K

            vec_D_loc_diff = vec_D_cen - list_mu_est[idx_ls].predict(mat_X_cen)

            vec_Y_loc_diff = vec_Y_cen - list_gamma_est[idx_ls].predict(mat_X_cen)
                            
            vec_U_loc_est = vec_Y_loc_diff - vec_D_cen * beta_est_ini
                            
            ## density ratio
            varU_loc = np.mean(np.power(vec_U_loc_est, 2))
            varU_cen = np.mean(np.power(vec_U_cen_est, 2))
            mat_U_slope[:, j] = np.power(vec_U_loc_est, 2)/(2*varU_loc) - np.power(vec_U_cen_est, 2)/(2*varU_cen)
            mat_U_slope[:, j] = np.exp(-1* mat_U_slope[:, j])
            mat_U_slope[:, j] = mat_U_slope[:, j] * math.sqrt(varU_cen)/math.sqrt(varU_loc)
            mat_U_slope[:, j] = mat_U_slope[:, j] * vec_D_cen * vec_D_loc_diff
            # mat_U_slope[:, j] = mat_U_slope[:, j] * vec_weight[j]
        U_slope = np.mean(mat_U_slope.sum(1))
        
        beta_est_cen = beta_est_ini + S / U_slope
        mat_beta_est_cen[j_cen, splt] = beta_est_cen


## final estimation
beta_est = np.mean(mat_beta_est_cen)
vec_beta_est_iter[i_iter] = beta_est
        
        
        
        
        
        
        
        
        
        
        
        
        
        

In [40]:
mat_beta_est_cen

array([[0.32953352, 0.31024512, 0.31764127],
       [0.33598084, 0.30024206, 0.31717861],
       [0.33364939, 0.30927443, 0.3163754 ]])

In [42]:
print("(Unweighted) mat_beta_est_cen: ", mat_beta_est_cen.mean(0))
print("(Unweighted) DDML estimator: ", mat_beta_est_cen.mean())

(Unweighted) mat_beta_est_cen:  [0.33305458 0.3065872  0.31706509]
(Unweighted) DDML estimator:  0.3189022923401904


## (Weighted) Naive Estimator

In [43]:
K=1
mat_beta_est_local = np.zeros((K, K_fold))

In [44]:

for splt in range(K_fold):
    idx_est1 = np.where(idx_K_fold[0] == splt)[0]
    idx_nui1 = np.where(idx_K_fold[0] != splt)[0]
    n_est1 = idx_est1.shape[0]
    idx_est2 = np.where(idx_K_fold[1] == splt)[0]
    idx_nui2 = np.where(idx_K_fold[1] != splt)[0]
    n_est2 = idx_est2.shape[0]
    idx_est3 = np.where(idx_K_fold[2] == splt)[0]
    idx_nui3 = np.where(idx_K_fold[2] != splt)[0]
    n_est3 = idx_est3.shape[0]
    ## training ML model
    mat_X_nui1 = df[0][idx_nui1, 6:20]
    vec_D_nui1 = df[0][idx_nui1, 22]
    vec_Y_nui1 = df[0][idx_nui1, 21]
    
    mat_X_nui2 = df[1][idx_nui2, 6:20]
    vec_D_nui2 = df[1][idx_nui2, 22]
    vec_Y_nui2 = df[1][idx_nui2, 21]
    
    mat_X_nui3 = df[2][idx_nui3, 6:20]
    vec_D_nui3 = df[2][idx_nui3, 22]
    vec_Y_nui3 = df[2][idx_nui3, 21]
                    
    ## estimating
    mat_X_est1 = df[0][idx_est1, 6:20]
    vec_D_est1 = df[0][idx_est1, 22]
    vec_Y_est1 = df[0][idx_est1, 21]
    
    mat_X_est2 = df[1][idx_est2, 6:20]
    vec_D_est2 = df[1][idx_est2, 22]
    vec_Y_est2 = df[1][idx_est2, 21]
    
    mat_X_est3 = df[2][idx_est3, 6:20]
    vec_D_est3 = df[2][idx_est3, 22]
    vec_Y_est3 = df[2][idx_est3, 21]
    
    
    model_mu1 = RandomForestRegressor(**param_d[0])
    model_mu1.fit(mat_X_nui1, vec_D_nui1)
    
    model_mu2 = RandomForestRegressor(**param_d[1])
    model_mu2.fit(mat_X_nui2, vec_D_nui2)
    
    model_mu3 = RandomForestRegressor(**param_d[2])
    model_mu3.fit(mat_X_nui3, vec_D_nui3)
                    
    ## estimation of beta based on partialling out score function
    model_xi1 = RandomForestRegressor(**param_y[0])
    model_xi1.fit(mat_X_nui1, vec_Y_nui1)
    
    model_xi2 = RandomForestRegressor(**param_y[1])
    model_xi2.fit(mat_X_nui2, vec_Y_nui2)
    
    model_xi3 = RandomForestRegressor(**param_y[2])
    model_xi3.fit(mat_X_nui3, vec_Y_nui3)
                    
    vec_D_diff1 = vec_D_est1 - model_mu1.predict(mat_X_est1)
    vec_Y_diff1 = vec_Y_est1 - model_xi1.predict(mat_X_est1)
    
    vec_D_diff2 = vec_D_est2 - model_mu2.predict(mat_X_est2)
    vec_Y_diff2 = vec_Y_est2 - model_xi2.predict(mat_X_est2)
    
    vec_D_diff3 = vec_D_est3 - model_mu3.predict(mat_X_est3)
    vec_Y_diff3 = vec_Y_est3 - model_xi3.predict(mat_X_est3)
    
    vec_Y_diff = np.concatenate((vec_Y_diff1,vec_Y_diff2,vec_Y_diff3))
    vec_D_diff = np.concatenate((vec_D_diff1,vec_D_diff2,vec_D_diff3))
                    
    beta_est_local = np.mean(vec_Y_diff * vec_D_diff) / np.mean(vec_D_diff * vec_D_diff)

    #model_gamma = RandomForestRegressor(n_estimators=n_rft)
    # model_gamma.fit(mat_X_nui, vec_Y_nui - vec_D_nui * beta_est_local)

    # list_mu_est.append(model_mu)
    # list_gamma_est.append(model_gamma)

    mat_beta_est_local[0, splt] = beta_est_local

beta_est_ini = np.mean(mat_beta_est_local)

#mat_beta_est_cen = np.zeros((K, K_fold))

In [45]:
mat_beta_est_local

array([[0.4167289 , 0.43772722, 0.36471558]])

In [46]:
print("(weighted) naive estimator: ", np.sum(mat_beta_est_local * vec_weight))
print("(unweighted) naive estimator: ", np.mean(mat_beta_est_local))

(weighted) naive estimator:  0.422065574022618
(unweighted) naive estimator:  0.40639056754459957


In [33]:
beta_est_ini

0.4033606806832741